const report = require('multiple-cucumber-html-reporter');
const path = require('path');
const fs = require('fs');

// Get metadata from package.json
const packageJson = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../package.json'), 'utf8'));

// Generate the enhanced HTML report
report.generate({
  jsonDir: path.resolve(__dirname, '../results'),
  reportPath: path.resolve(__dirname, '../results/enhanced-html-report'),
  metadata: {
    browser: {
      name: 'Chromium',
      version: 'Latest',
    },
    device: 'Local Test Machine',
    platform: {
      name: process.platform,
      version: process.version,
    },
  },
  customData: {
    title: 'Test Execution Report',
    data: [
      { label: 'Project', value: packageJson.name },
      { label: 'Version', value: packageJson.version },
      { label: 'Execution Date', value: new Date().toISOString() },
      { label: 'Framework', value: 'Playwright + Cucumber' },
    ],
  },
  pageTitle: 'Playwright-Cucumber Test Report',
  reportName: 'Test Automation Report',
  pageFooter: `<div style="text-align: center;">
    <p>Generated by ${packageJson.name} v${packageJson.version}</p>
  </div>`,
  displayDuration: true,
  displayReportTime: true,
  durationInMS: true,
});

console.log('✅ Enhanced HTML report generated successfully at: results/enhanced-html-report');
